# Language frameworks, library packages, CLI tools
# For openjdk, run setup_openjdk.zsh
# For python, set stable version
# For fzf, source the completions in ~/.zshrc
# For go, java, rust, llvm, set PATH references in ~/.zprofile
# For c/c++ libraries, set CFLAGS and LDFLAGS appropriately
brew "bat"
brew "boost"
brew "cfr-decompiler"
brew "cmake"
brew "cppcheck"
brew "coreutils"
brew "dos2unix"
brew "dust"
brew "eza"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "ghc"
brew "ghcup"
brew "git"
brew "go"
brew "golangci-lint"
brew "goreleaser"
brew "gotestsum"
brew "gradle"
brew "hugo"
brew "jq"
brew "kotlin"
brew "ktfmt"
brew "lefthook"
brew "llvm"
brew "maven"
brew "mockery"
brew "neovim"
brew "ninja"
brew "nmap"
brew "node"
brew "numpy"
brew "openjdk@17"
brew "openjdk@21"
brew "poetry"
brew "protobuf"
brew "pstree"
brew "python@3.12"
brew "python@3.13"
brew "python@3.14"
brew "ripgrep"
brew "ruff"
brew "rust"
brew "sbt"
brew "scc"
brew "scala"
brew "staticcheck"
brew "tcpdump"
brew "tealdeer"
brew "tree"
brew "uv"
brew "vhs"
brew "vineflower"
brew "yt-dlp"
brew "zig"
brew "zoxide"

# Casks applications
# Run `brew upgrade --cask --greedy` for personal machines, NOT work machines
cask "dbeaver-community"
cask "discord"
cask "font-hack-nerd-font"
cask "ghostty"
cask "jetbrains-toolbox"
cask "postman"
cask "redis-insight"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "xcodes-app"
cask "zoom"
