name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dotfile-build:
    name: Dotfiles
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Brewfile contents
        run: |
          brew bundle list
      - name: Install zsh shell
        run: |
          brew install zsh
      - name: Run combine script
        run: combine.zsh
      - name: Run copy script
        run: copy.zsh
