name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dotfile-build:
    name: Dotfiles
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check default shell
        run: |
          echo $SHELL
      - name: Run combine script
        run: |
          ./combine.zsh
      - name: Run copy script
        run: |
          ./copy.sh
      - name: Check Brewfile contents
        run: |
          brew bundle list
