name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dotfile-build:
    name: Dotfiles
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Brewfile contents
        run: brew bundle list
      - name: Setup zsh and shellcheck
        run: brew install zsh shellcheck
      - name: Run combine script
        run: zsh combine.zsh override
      - name: Validate combine script
        run: shellcheck --shell=bash /home/runner/.zsh_aliases
      - name: Run copy script
        run: zsh copy.zsh override
      - name: Validate copy script
        run: git la
